//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTW_HQK_shop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaiViet
    {
        public string mabv { get; set; }
        public string tenbv { get; set; }
        public string hinhDD { get; set; }
        public string ndtomtat { get; set; }
        public string noidung { get; set; }
        public string taikhoan { get; set; }
        public Nullable<System.DateTime> ngaydang { get; set; }
        public string loaitin { get; set; }
        public Nullable<bool> daduyet { get; set; }
    
        public virtual Adminn Adminn { get; set; }
    }
}
