//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTW_HQK_shop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chiTietDH
    {
        public int idctdh { get; set; }
        public Nullable<int> maSP { get; set; }
        public Nullable<int> iddh { get; set; }
        public int soLuong { get; set; }
        public double giaBan { get; set; }
    
        public virtual donHang donHang { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
