//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTW_HQK_shop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class donHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public donHang()
        {
            this.chiTietDHs = new HashSet<chiTietDH>();
        }
    
        public int iddh { get; set; }
        public string makh { get; set; }
        public string taikhoan { get; set; }
        public string tenKH { get; set; }
        public System.DateTime ngaydat { get; set; }
        public string soDT { get; set; }
        public string eMail { get; set; }
        public string diachigiaohang { get; set; }
    
        public virtual Adminn Adminn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chiTietDH> chiTietDHs { get; set; }
        public virtual Khachhang Khachhang { get; set; }
    }
}
