//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTW_HQK_shop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.chiTietDHs = new HashSet<chiTietDH>();
        }
    
        public int maSP { get; set; }
        public int maLoai { get; set; }
        public string taikhoan { get; set; }
        public string tenSP { get; set; }
        public string tenLoai { get; set; }
        public double giaBan { get; set; }
        public double gianiemyet { get; set; }
        public string hinhDD { get; set; }
        public string ndtomtat { get; set; }
        public Nullable<bool> daduyet { get; set; }
        public Nullable<int> soluong { get; set; }
        public string mota1 { get; set; }
        public string mota2 { get; set; }
        public string mota3 { get; set; }
        public string chitiet1 { get; set; }
        public string chitiet2 { get; set; }
        public string chitiet3 { get; set; }
        public System.DateTime ngaydang { get; set; }
    
        public virtual Adminn Adminn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chiTietDH> chiTietDHs { get; set; }
        public virtual LoaiSP LoaiSP { get; set; }
    }
}
